version: '3.3'

services:
   subreddit:
     image: scrap_subreddit
     build:
       context: ./scrap_subreddit
       dockerfile: Dockerfile
     env_file: dev.env
     volumes:
       - ./output:/output/:rw
     depends_on:
       - elasticsearch
       - scrapyd
   elasticsearch:
     image: elasticsearch:7.5.1
     environment:
       - discovery.type=single-node
   scrapyd:
     container_name: scrapyd
     image: scrapyd
     build:
       context: ./scrapyd
     restart: always
     env_file: dev.env
     ports:
       - "0:6800:6800"