version: '3.3'

services:

   frontend:
    image: frontend
    build:
      context: frontend
    depends_on:
      - backend
    ports:
      - 0:80:80
   subreddit:
     image: scrap_subreddit
     build:
       context: ./scrap_subreddit
       dockerfile: Dockerfile
     env_file: dev.env
     depends_on:
       - elasticsearch
       - scrapyd
   elasticsearch:
     image: elasticsearch:7.5.1
     environment:
       - discovery.type=single-node
     logging:
       driver: none 
   scrapyd:
     container_name: scrapyd
     image: scrapyd
     build:
       context: ./scrapyd
     restart: always
     env_file: dev.env
     ports:
       - "0:6800:6800"
   backend:
     image: backend
     env_file: dev.env
     build:
       context: backend
     depends_on:
       - elasticsearch
       - scrapyd
     ports:
       - 0:5000:5000

   rabbitmq:
     image: rabbitmq:3.7.8-management-alpine
     ports:
       - 15672:15672

   celery_worker:
     depends_on:
       - rabbitmq
       - backend
     image: celery_worker
     env_file: dev.env
     build:
      context: scrap_twitter_celery_worker
      