version: '3.3'

services:
   subreddit:
     image: scrap_subreddit
     build:
       context: ./scrap_subreddit
       dockerfile: Dockerfile
     environment:
       - max_number_of_scrapped_pages=5
       - sub_reddit=flask
     volumes:
       - ./output:/output/:rw
  #    depends_on:
  #      - splash
  #  splash:
  #    image: scrapinghub/splash
